# Dependencies

# kramdown to support footnotes
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title

# Setup
title:            david h. colmenares 
tagline:          ''
description:      ''
url:              https://hipomenes.github.io

# Required if you want to move pages into a a separate directory
include: ['_pages']
relative_permalinks: false

author:
  name:           'David H. Colmenares'
  url:            https://hipomenes.github.io

# Custom vars

github:
  repo:          https://github.com/hipomenes
